version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: bdx3
    container_name: bdx3
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bdx3
      POSTGRES_USER: bdx3
      POSTGRES_PASSWORD: bdx3
      PGDATA: /var/lib/postgresql/data/bdx3
    volumes:
      - bdx3:/var/lib/postgresql/data

volumes:
  bdx3:
